[package]
name = "escrow"
version = "0.1.0"
authors = ["Steven Chang <steven.chang@btn.group>"]
edition = "2021"

[dependencies]
ink = { version = "~4.2.0", default-features = false}

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2.3", default-features = false, features = ["derive"], optional = true }

openbrush = { git = "https://github.com/727-Ventures/openbrush-contracts", version = "~3.1.1", default-features = false, features = ["ownable"] }
ink_prelude = {git = "https://github.com/paritytech/ink", package = "ink_prelude", default-features = false }

[lib]
name = "escrow"
path = "lib.rs"
crate-type = [
	# Used for normal contract Wasm blobs.
	"cdylib",
]

[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",
    # Brush dependency
    "openbrush/std",
]
ink-as-dependency = []
